---
- hosts: servers
  tasks:
    - name: Install python3 and virtualenv
      become: yes
      apt:
        pkg: 
          - python3
          - virtualenv
        update_cache: yes
    - name: Pip requirements
      pip:
        virtualenv: ${HOME}/.venv
        name:
          - django
          - djangorestframework
    - name: Start project
      shell: |
        . ${HOME}/.venv/bin/activate
        django-admin startproject setup . 
    - name: Update line-in-file
      lineinfile:
        path: ${HOME}/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
...