---
- hosts: servers
  tasks:
    - name: Install python3 and virtualenv
      become: yes
      apt:
        pkg: 
          - python3
          - virtualenv
        update_cache: yes

    - name: Git clone
      ansible.builtin.git:
        repo: https://github.com/alura-cursos/clientes-leo-api
        dest: /home/ubuntu/tcc
        version: master
        force: yes

    - name: Pip requirements
      pip:
        virtualenv: ${HOME}/tcc/.venv
        requirements: ${HOME}/tcc/requirements.txt

    - name: Update line-in-file
      lineinfile:
        path: ${HOME}/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
    
    - name: Database migrations
      shell: |
        . ${HOME}/tcc/.venv/bin/activate
        python3 ${HOME}/tcc/manage.py migrate
    
    - name: Database input data
      shell: |
        . ${HOME}/tcc/.venv/bin/activate
        python3 ${HOME}/tcc/manage.py loaddata clientes.json
...